// Auto-generated by fetch-sefaria.ts — do not edit manually
// Source: Sefaria API (https://www.sefaria.org)
// Generated: 2026-03-06T20:18:13.910Z

import type { Tefila, PrayerSection } from "../types";

export const otherAsherYatzarEtchemBadin: Tefila = {
  id: "other-asher-yatzar-etchem-badin",
  name: "Asher Yatzar Etchem Badin",
  nameHe: "ברכות",
  category: "other",
  timeContext: "anytime",
  sections: [
  {
    id: "asher-yatzar-etchem-badin-asher-yatzar-etchem-badin",
    title: "Asher Yatzar Etchem Badin",
    titleHe: "מחיה המתים",
    instruction: `ברוך אתה יי אלהינו מלך העולם, אשר יצר אתכם בדין, וזן וכלכל אתכם בדין, והמית אתכם בדין, ויודע מספר כלכם בדין, והוא עתיד להחיותכם ולקים אתכם בדין. ברוך אתה ד', מחיה המתים.`,
    text: `ברוך אתה יי אלהינו מלך העולם, אשר יצר אתכם בדין, וזן וכלכל אתכם בדין, והמית אתכם בדין, ויודע מספר כלכם בדין, והוא עתיד להחיותכם ולקים אתכם בדין. ברוך אתה ד', מחיה המתים.`,
    translation: ``,
  },
  ],
};

export const ALL_ASHER_YATZAR_ETCHEM_BADIN: Tefila[] = [
  otherAsherYatzarEtchemBadin,
];
