// Auto-generated by fetch-sefaria.ts — do not edit manually

import type { Tefila } from "../types";
import { ALL_SHACHARIT } from "./shacharit";
import { ALL_MINCHAH } from "./minchah";
import { ALL_MAARIV } from "./maariv";
import { ALL_SHABBAT_KABBALAT_SHABBAT } from "./shabbat-kabbalat-shabbat";
import { ALL_SHABBAT_MAARIV } from "./shabbat-maariv";
import { ALL_SHABBAT_SHABBAT_EVENING } from "./shabbat-shabbat-evening";
import { ALL_SHABBAT_SHACHARIT } from "./shabbat-shacharit";
import { ALL_SHABBAT_MUSAF_LESHABBAT } from "./shabbat-musaf-leshabbat";
import { ALL_SHABBAT_DAYTIME_MEAL } from "./shabbat-daytime-meal";
import { ALL_SHABBAT_MINCHAH } from "./shabbat-minchah";
import { ALL_SHABBAT_THIRD_MEAL } from "./shabbat-third-meal";
import { ALL_SHABBAT_HAVDALAH } from "./shabbat-havdalah";
import { ALL_FESTIVALS_ROSH_CHODESH } from "./festivals-rosh-chodesh";
import { ALL_FESTIVALS_SHALOSH_REGALIM } from "./festivals-shalosh-regalim";
import { ALL_FESTIVALS_PRAYER_FOR_DEW } from "./festivals-prayer-for-dew";
import { ALL_FESTIVALS_PRAYER_FOR_RAIN } from "./festivals-prayer-for-rain";
import { ALL_FESTIVALS_SUKKOT } from "./festivals-sukkot";
import { ALL_FESTIVALS_CHANUKAH } from "./festivals-chanukah";
import { ALL_FESTIVALS_SELICHOT } from "./festivals-selichot";
import { ALL_BIRKAT_HAMAZON } from "./birkat-hamazon";
import { ALL_BIRKAT_HANEHENIN } from "./birkat-hanehenin";
import { ALL_BIRKHOT_HAMITZVOT } from "./birkhot-hamitzvot";
import { ALL_ASHER_YATZAR_ETCHEM_BADIN } from "./asher-yatzar-etchem-badin";
import { ALL_TEFILLAT_HADERECH } from "./tefillat-haderech";
import { ALL_HAVINENU } from "./havinenu";
import { ALL_KADDISH } from "./kaddish";
import { ALL_BLESSINGS_ADDITIONAL } from "./blessings-additional";
import { ALL_LIFECYCLE_BRIS_PIDYON } from "./lifecycle-bris-pidyon";
import { ALL_LIFECYCLE_MOURNING } from "./lifecycle-mourning";

export { ALL_INSERTIONS } from "./insertions";

export const ALL_TEFILOS: Tefila[] = [
  ...ALL_SHACHARIT,
  ...ALL_MINCHAH,
  ...ALL_MAARIV,
  ...ALL_SHABBAT_KABBALAT_SHABBAT,
  ...ALL_SHABBAT_MAARIV,
  ...ALL_SHABBAT_SHABBAT_EVENING,
  ...ALL_SHABBAT_SHACHARIT,
  ...ALL_SHABBAT_MUSAF_LESHABBAT,
  ...ALL_SHABBAT_DAYTIME_MEAL,
  ...ALL_SHABBAT_MINCHAH,
  ...ALL_SHABBAT_THIRD_MEAL,
  ...ALL_SHABBAT_HAVDALAH,
  ...ALL_FESTIVALS_ROSH_CHODESH,
  ...ALL_FESTIVALS_SHALOSH_REGALIM,
  ...ALL_FESTIVALS_PRAYER_FOR_DEW,
  ...ALL_FESTIVALS_PRAYER_FOR_RAIN,
  ...ALL_FESTIVALS_SUKKOT,
  ...ALL_FESTIVALS_CHANUKAH,
  ...ALL_FESTIVALS_SELICHOT,
  ...ALL_BIRKAT_HAMAZON,
  ...ALL_BIRKAT_HANEHENIN,
  ...ALL_BIRKHOT_HAMITZVOT,
  ...ALL_ASHER_YATZAR_ETCHEM_BADIN,
  ...ALL_TEFILLAT_HADERECH,
  ...ALL_HAVINENU,
  ...ALL_KADDISH,
  ...ALL_BLESSINGS_ADDITIONAL,
  ...ALL_LIFECYCLE_BRIS_PIDYON,
  ...ALL_LIFECYCLE_MOURNING,
];

/**
 * Get all tefilos matching a given time context (shacharis, mincha, maariv, anytime).
 */
export function getTefilosForTime(
  timeContext: "shacharis" | "mincha" | "maariv" | "anytime"
): Tefila[] {
  return ALL_TEFILOS.filter(
    (t) => t.timeContext === timeContext || t.timeContext === "anytime"
  );
}

/**
 * Find a single tefila by its ID.
 */
export function getTefilaById(id: string): Tefila | undefined {
  return ALL_TEFILOS.find((t) => t.id === id);
}

/**
 * Get all tefilos matching a given category.
 */
export function getTefilosByCategory(
  category: Tefila["category"]
): Tefila[] {
  return ALL_TEFILOS.filter((t) => t.category === category);
}
